# Generated by Django 4.2.10 on 2024-08-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_current_planet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_planet',
        ),
    ]
