# Generated by Django 4.2.10 on 2024-05-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iron',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
