# Generated by Django 4.2.10 on 2024-08-01 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iron',
            name='player',
        ),
    ]
