# Generated by Django 4.2.10 on 2024-05-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_player_iron'),
        ('resources', '0002_alter_iron_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='iron',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='players.player'),
        ),
    ]
