# Generated by Django 4.2.10 on 2024-09-28 18:07

from django.db import migrations, models
import django_lifecycle.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_iron_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='IronMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
