# Generated by Django 4.2.10 on 2024-09-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_planet_iron'),
        ('resources', '0003_ironmine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ironmine',
            name='planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planets.planet'),
        ),
    ]
