# Generated by Django 4.2.10 on 2024-09-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_ironmine_planet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ironmine',
            name='iron',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iron_mine', to='resources.iron'),
        ),
    ]
