# Generated by Django 4.2.10 on 2024-09-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_iron_mine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iron',
            name='mine',
        ),
    ]
