# Generated by Django 4.2.10 on 2024-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_iron_mine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ironmine',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
