# Generated by Django 4.2.10 on 2024-09-28 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_iron_planet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iron',
            name='mine',
        ),
        migrations.AddField(
            model_name='ironmine',
            name='iron',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mine', to='resources.iron'),
            preserve_default=False,
        ),
    ]
