# Generated by Django 4.2.10 on 2024-10-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_ironmine_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ironmine',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
