# Generated by Django 4.2.10 on 2024-05-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_update',
        ),
    ]
