# Generated by Django 4.2.10 on 2024-09-28 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_planet_iron'),
        ('players', '0003_remove_player_iron'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_planet', to='planets.planet'),
        ),
    ]
