# Generated by Django 4.2.10 on 2024-05-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('players', '0003_remove_player_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='iron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resources.iron'),
        ),
    ]
