# Generated by Django 4.2.10 on 2024-05-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_iron_quantity'),
        ('players', '0006_remove_player_id_alter_player_iron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='iron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='resources.iron'),
        ),
    ]
