# Generated by Django 4.2.10 on 2024-05-21 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_iron_quantity'),
        ('players', '0007_alter_player_iron'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='iron',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.iron'),
        ),
    ]
