# Generated by Django 4.2.10 on 2024-05-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_iron_quantity'),
        ('players', '0008_player_id_alter_player_iron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='iron',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_iron', to='resources.iron'),
        ),
    ]
