# Generated by Django 4.2.10 on 2024-08-01 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('planets', '0002_planet_home_planet'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='iron',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planet_iron', to='resources.iron'),
        ),
    ]
