# Generated by Django 4.2.10 on 2024-09-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_ironmine_planet'),
        ('planets', '0003_planet_iron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='iron',
        ),
        migrations.AddField(
            model_name='planet',
            name='iron_mine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planet_mine', to='resources.ironmine'),
        ),
    ]
