# Generated by Django 4.2.10 on 2024-09-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_planet_iron'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='iron',
        ),
    ]
